import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { PwaRegister } from "@/components/pwa-register";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "WorkoutMate — Your Personal AI Fitness Coach",
    template: "%s — WorkoutMate",
  },
  description:
    "Get a personalised workout plan, track your progress and train with an AI fitness coach built around your goals.",
  applicationName: "WorkoutMate",
  keywords: [
    "fitness app",
    "AI fitness coach",
    "workout planner",
    "personal trainer app",
    "workout tracker",
    "strength training",
  ],
  authors: [{ name: "WorkoutMate" }],
  manifest: "/manifest.webmanifest",
  // Favicon / apple-icon / og-image / twitter-image are all generated by the
  // app/icon.tsx, app/apple-icon.tsx and app/opengraph-image.tsx file
  // conventions — Next.js wires them into <head> automatically.
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "WorkoutMate",
    title: "WorkoutMate — Your Personal AI Fitness Coach",
    description:
      "Get a personalised workout plan, track your progress and train with an AI fitness coach built around your goals.",
  },
  twitter: {
    card: "summary_large_image",
    title: "WorkoutMate — Your Personal AI Fitness Coach",
    description:
      "Get a personalised workout plan, track your progress and train with an AI fitness coach built around your goals.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "hsl(220 20% 99%)" },
    { media: "(prefers-color-scheme: dark)", color: "hsl(224 26% 6%)" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
          <Toaster />
          <PwaRegister />
        </ThemeProvider>
      </body>
    </html>
  );
}
